from typing import Literal, NotRequired, TypedDict


class SongData(TypedDict):
    title: str
    dlc: NotRequired[int | Literal["free"]]


# fmt: off
songs: list[SongData] = [
    # this song doesn't seem to exist??
    # {"title": "A flower blooming on phantasm"},
    {"title": "Akaboshi Mizeraburu ~Haiokuhen"},
    {"title": "Akeboshi Rocket"},
    {"title": "An stoirm"},
    {"title": "Bad Apple!! feat.nomico"},
    {"title": "Blaze Up Song"},
    {"title": "Border of Life"},
    {"title": "Breaking the Silence"},
    {"title": "Cirno no Perfect Sansuu Kyoushitsu"},
    {"title": "Crimson Belvedere ~ Eastern Dream..."},
    {"title": "Danzai ha Amaneku Ningen no Motoni"},
    {"title": "DREAMIN' TURBO [DJ Command Remix]"},
    {"title": "drizzly rain"},
    {"title": "Ecstatic Dreamers"},
    {"title": "Epikurosu no niji ha moumienai"},
    {"title": "Fall of Fall"},
    {"title": "Fox Bullet"},
    {"title": "Fragments"},
    {"title": "From Lost To Exequistra"},
    {"title": "Gensoukyou Fushigi Daihakken V2"},
    {"title": "Hakanakimono Ningen"},
    {"title": "HANIPAGANDA"},
    {"title": "Hartmann's Youkai Girl"},
    {"title": "Haruka Tooku Haruka Kanata"},
    {"title": "Help me, ERINNNNNN!!"},
    {"title": "Iroha Nioedo Cirinuruwo"},
    {"title": "Kakoinaki Yo wa Ichigo no Tsukikage"},
    {"title": "Karakuri Doll"},
    {"title": "Karma D-Live"},
    {"title": "Kegarematoitekagomekagome"},
    {"title": "Knight of Nights"},
    {"title": "Kuroi Umi ni Akaku ~Legendary Fish"},
    {"title": "Kyousyuu no Rondo"},
    {"title": "Live or live!"},
    {"title": "LOSTPHANTASIA"},
    {"title": "Lucent Wish"},
    {"title": "Machibito ha Kozu."},
    {"title": "MATSUYOI Nightbug"},
    {"title": "Meguru Harvest"},
    {"title": "Mischievous Sensation"},
    {"title": "Native Faith（Dankagu special ver.）"},
    {"title": "Night Flight Believer"},
    {"title": "Ougon Kouro"},
    {"title": "Phantom Band ~ Phantom Ensemble"},
    {"title": "Pure Furies ~ Whereabouts of the Heart"},
    {"title": "Re:Unknown X"},
    {"title": "Reach for the Moon, Immortal Smoke"},
    {"title": "Reisen Occultia [Touhou Shinpiroku Re:Arange]", },
    {"title": "Resonance ~ What Makes Me Who I Am"},
    {"title": "Sadistic Love - Danmakukagura Edit"},
    {"title": "Saishuu kichiku imouto Flandre-S"},
    {"title": "Sayounara. Arigatou."},
    {"title": "Scarlet Keisatsu no Ghetto Patrol 24ji"},
    {"title": "snow amber Remix"},
    {"title": "Spider's Blood"},
    {"title": "Spring of Dreams"},
    {"title": "Starlight Dance Floor (D.M.K. edit)"},
    {"title": "Tengu no Hana（feat.TAG）"},
    {"title": "Tenimuhou"},
    {"title": "The Mirage of That Day"},
    {"title": "Tsuki ni Murakumo Hana ni Kaze"},
    {"title": "Ttewi! ~Eientewi Ver~"},
    {"title": "U.N. Owen Was Her?"},
    {"title": "Unprivileged Access"},
    {"title": "Uso to Doukoku"},
    {"title": "White Lotus..."},
    {"title": "Yozora to Ningyou"},
    {"title": "Yukemuri TamaOnSen II"},

    {"title": "Bad Apple!! feat.nomico (Tetsuya Komuro Remix)", "dlc": 1, },
    {"title": "Christmas Bomb!!", "dlc": 1},
    {"title": "Dial Connected", "dlc": 1},
    {"title": "Entrusting this World to Idols(marasy piano ver.)", "dlc": 1, },
    {"title": "Genmu", "dlc": 1},
    {"title": "Gensou no Satellite", "dlc": 1},
    {"title": "Gensou Syndrome", "dlc": 1},
    {"title": "Hanamaru! Saikyo Hyper Cirno", "dlc": 1},
    {"title": "Hell's Sun", "dlc": 1},
    {"title": "Hitorisizuka（Marcia Cover Version）", "dlc": 1},
    {"title": "Howling", "dlc": 1},
    {"title": "INTERNET SURVIVOR", "dlc": 1},
    {"title": "Love-colored Master Spark", "dlc": 1},
    {"title": "M. O. N. E. Y. (Dankagu Special REMIX Ver.)", "dlc": 1, },
    {"title": "Museimei Saafesu", "dlc": 1},
    {"title": "Onerule・Gamechanger", "dlc": 1},
    {"title": "PanneDemonology", "dlc": 1},
    {"title": "Paranoia", "dlc": 1},
    {"title": "POKER FACE", "dlc": 1},
    {"title": "SACRIFICE", "dlc": 1},
    {"title": "Saigetsu", "dlc": 1},
    {"title": "Tenkyuu Tenge Otohanabi", "dlc": 1},
    {"title": "The Karasu Wind", "dlc": 1},
    {"title": "Trance Dance Anarcky", "dlc": 1},
    {"title": "Uki Yomichi (feat. Ranko, Utenkekkou)", "dlc": 1},

    {"title": "Against, Perfect Cherry Blossom", "dlc": 2},
    {"title": "Amatsukazeyo", "dlc": 2},
    {"title": "Can't look away", "dlc": 2},
    {"title": "Desire Drive", "dlc": 2},
    {"title": "far away", "dlc": 2},
    {"title": "Flower Flag", "dlc": 2},
    {"title": "Gensokyo Millennium ~ History of the Moon", "dlc": 2, },
    {"title": "Hitotsuyogari no Touhikou", "dlc": 2},
    {"title": "King of the Sekkyou", "dlc": 2},
    {"title": "LOVE EAST", "dlc": 2},
    {"title": "Mami Mami Zone", "dlc": 2},
    {"title": "Marisa Stole the Precious Thing", "dlc": 2},
    {"title": "Never Come Undone", "dlc": 2},
    {"title": "Painting The Lips Red", "dlc": 2},
    {"title": "Pandora", "dlc": 2},
    {"title": "Rainy, rainy days", "dlc": 2},
    {"title": "SAMURAI GHOST GIRL, KILL! KILL!", "dlc": 2},
    {"title": "Scream out!", "dlc": 2},
    {"title": "Shinreibyou Akimatsuri!", "dlc": 2},
    {"title": "Shout It Out Loud!!!", "dlc": 2},
    {"title": "Shoutoku Densetsu ~ True Administrator", "dlc": 2},
    {"title": "SWEET BLUE ICE", "dlc": 2},
    {"title": "Tiny Little Adiantum", "dlc": 2},
    {"title": "Utakata, Ai no Mahoroba", "dlc": 2},
    {"title": "Youyoubakko ~ Who done it!", "dlc": 2},

    {"title": "23145EASONS", "dlc": 3},
    {"title": "Aestivalis(Danmakukagura Edit)", "dlc": 3},
    {"title": "Aitsu ha Ikasama wo Shiteiru", "dlc": 3},
    {"title": "Atashimania", "dlc": 3},
    {"title": "Aunn by me", "dlc": 3},
    {"title": "Ayakashi set 14 Another ~Yoru ga Oritekuru", "dlc": 3, },
    {"title": "BURN IN HELL", "dlc": 3},
    {"title": "Chi no Iro ha Kiiro", "dlc": 3},
    {"title": "Ford Stream", "dlc": 3},
    {"title": "Gekokujoujou", "dlc": 3},
    {"title": "Gensou Kappa Kousinkyoku(feat.ｙｔｒ)", "dlc": 3},
    {"title": "Hands(feat. AO, Rappubito)", "dlc": 3},
    {"title": "hareruya ga kikoeru", "dlc": 3},
    {"title": "Hollow Masquerade", "dlc": 3},
    {"title": "Kachoufuugetsu", "dlc": 3},
    {"title": "Kagerou-chan Tsuki ni Hoeru (Dankagu Edit)", "dlc": 3, },
    {"title": "Konya, Syojo jya Irarenai", "dlc": 3},
    {"title": "Liminality", "dlc": 3},
    {"title": "Night's Dream (D.M.K. edit)", "dlc": 3},
    {"title": "SEE YOU AGAIN!", "dlc": 3},
    {"title": "Solid", "dlc": 3},
    {"title": "Sweets Time", "dlc": 3},
    {"title": "The Shining Law of the Strong Eating the Weak", "dlc": 3, },
    {"title": "Unconscious Requiem（cosmobsp rmx）", "dlc": 3},
    {"title": "USATEI 20XX", "dlc": 3},
    {"title": "WARNING×WARNING×WARNING", "dlc": 3},

    {"title": "Akutagawa Ryuunosuke no Kappa", "dlc": 4},
    {"title": "Charisma Rengoku Tenshin", "dlc": 4},
    {"title": "Dancing Dollz feat. cold kiss", "dlc": 4},
    {"title": "Fabulous", "dlc": 4},
    {"title": "flanticnight", "dlc": 4},
    {"title": "GAME OVER (In Disarray)", "dlc": 4},
    {"title": "Getsurei 11.3 no Candle Magic", "dlc": 4},
    {"title": "Hakurei Jinja Chounaikai Ondo", "dlc": 4},
    {"title": "HAZARD☢AREA", "dlc": 4},
    {"title": "Hopeless Discord", "dlc": 4},
    {"title": "Hoshi wo Mawase Tsuki yori Hayaku", "dlc": 4},
    {"title": "Iconoclasm", "dlc": 4},
    {"title": "Ilias", "dlc": 4},
    {"title": "Kanbu de Tomatte Sugu Tokeru ~Kyouki no Udongein", "dlc": 4, },
    {"title": "Kyouen", "dlc": 4},
    {"title": "Lezamari demo tsurakunai!!", "dlc": 4},
    {"title": "Lotus Love", "dlc": 4},
    {"title": "Marionette Metropolis", "dlc": 4},
    {"title": "Mishaguji Empire", "dlc": 4},
    {"title": "Non-Stop Ringing Heartbeats", "dlc": 4},
    {"title": "Romantic Fall feat. Ayakura Mei", "dlc": 4},
    {"title": "Septette for a Dead Princess", "dlc": 4},
    {"title": "Shunkan Photography", "dlc": 4},
    {"title": "sparkle light", "dlc": 4},
    {"title": "supernatural", "dlc": 4},
    {"title": "Tenshi no Udedameshi", "dlc": 4},
    {"title": "VOLUPTÉ (Game Edit)", "dlc": 4},

    {"title": "Heaven and earth are ruled by my [X]VII divine light", "dlc": 5, },
    {"title": "Love-Colored Master Spark ~ NEETs ver.", "dlc": 5},
    {"title": "Rock 'n' Rock 'n' Beat", "dlc": 5},
    {"title": "Saishuu kichiku imouto Flandre-S(Sasuke Haraguchi was Brutal? remix)", "dlc": 5, },
    {"title": "Sekai Hifuu Club-ka Keikaku", "dlc": 5},
    {"title": "Stairway to Cherry Blossoms", "dlc": 5},
    {"title": "The Footsteps That Summon Winter", "dlc": 5},
    {"title": "The Gensoukyou the Gods Loved", "dlc": 5},
    {"title": "Ultimate taste", "dlc": 5},
    {"title": "Wind of Faith", "dlc": 5},

    {"title": "HUNDRED DUOVIGINTILLION ARROWS", "dlc": 6},
    {"title": "Idoratrize World", "dlc": 6},
    {"title": "Lamento (Dankagu Edit)", "dlc": 6},
    {"title": "Nobody Can Stop Bankichan", "dlc": 6},
    {"title": "Rough Sea (Game Edit)", "dlc": 6},
    {"title": "Subliminal Seduction", "dlc": 6},
    {"title": "Tenacity", "dlc": 6},
    {"title": "The World Is Made From Cuteness", "dlc": 6},
    {"title": "Tsukikake (feat. Coro)", "dlc": 6},
    {"title": "Witches Rule (SIRIUS Remix)", "dlc": 6},

    {"title": "・ー・・ ーーー ・・・ー ・", "dlc": 7},
    {"title": "Crepusculum", "dlc": 7},
    {"title": "Desire Drive", "dlc": 7},
    {"title": "Exteeend!!", "dlc": 7},
    {"title": "Futeikei Avatar", "dlc": 7},
    {"title": "Kowareta Ningyo no March (SA ver.)", "dlc": 7},
    {"title": "Midnight Syndrome", "dlc": 7},
    {"title": "Mishery", "dlc": 7},
    {"title": "sharp edge", "dlc": 7},
    {"title": "STNC", "dlc": 7},

    {"title": "5byo Kakumei Zen'ya", "dlc": 8},
    {"title": "Heart in Wonderland", "dlc": 8},
    {"title": "HEAT WAVER!(feat. Rappubito, Fra)", "dlc": 8},
    {"title": "Hiiro Gekka Kyosho no Zetsu 15th Anniversary Remix nayuta.ver", "dlc": 8, },
    {"title": "Maiden's Capriccio ~ Dream Battle", "dlc": 8},
    {"title": "myth?", "dlc": 8},
    {"title": "PRESERVED VAMPIRE", "dlc": 8},
    {"title": "Re:Border of Life", "dlc": 8},
    {"title": "Touhou Youyoumu ~the maximum moving about~", "dlc": 8, },
    {"title": "Utakata", "dlc": 8},

    {"title": "Absolute Queen", "dlc": 9},
    {"title": "Alice Maestera(REBIRTHED)", "dlc": 9},
    {"title": "Calamity Fortune", "dlc": 9},
    {"title": "Entrust This World to Idols ~ Idolatrize World", "dlc": 9, },
    {"title": "kero9destiny - type130", "dlc": 9},
    {"title": "Kodoku Tsuki", "dlc": 9},
    {"title": "Necromantic", "dlc": 9},
    {"title": "Star-Colored Night Sky", "dlc": 9},
    {"title": "Syuki Rai Rai!", "dlc": 9},
    {"title": "Xeno Phantasm", "dlc": 9},

    {"title": "A Soul as Scarlet as a Ground Cherry", "dlc": 10},
    {"title": "Bang Bang!", "dlc": 10},
    {"title": "DA-DA-ON-SEN (feat. Utenkekkou)", "dlc": 10},
    {"title": "Flame of Nuclear (Dankagu Edit)", "dlc": 10},
    {"title": "Lunatic Princess", "dlc": 10},
    {"title": "Night Falls ～ Evening Star LSDj Remix (Dankagu Edit)", "dlc": 10, },
    {"title": "Sunlight Diamonds (Violet Delta Remix)", "dlc": 10},
    {"title": "The Replica Sneers", "dlc": 10},
    {"title": "Vampire Mate", "dlc": 10},
    {"title": "Who killed U.N.Owen", "dlc": 10},

    {"title": "Call of Mirage (Game Edit)", "dlc": 11},
    {"title": "Kare Kishi ni Saku", "dlc": 11},
    {"title": "MagicPhilia (Chimera Edit)", "dlc": 11},
    {"title": "New Arrangement by D-Drive vs. pomaira m9(^Д^)", "dlc": 11, },
    {"title": "New Arrangement by Galactic Revolver × UNKNOWN BEATS", "dlc": 11, },
    {"title": "New Arrangement by INORAI / Girls Logic Observatory / AbsoЯute Zero", "dlc": 11, },
    {"title": "New Arrangement by Sekkenya feat. beatMARIO", "dlc": 11, },
    {"title": "Take Thy Danmaku In Hand, O Bulletphiles", "dlc": 11, },
    {"title": "Twin Tailed Step", "dlc": 11},
    {"title": "Voile, the Magic Library (Jazz & Chill Edit)", "dlc": 11, },

    {"title": "A Dream Transcending Space-time", "dlc": 12},
    {"title": "Armageddon", "dlc": 12},
    {"title": "Arrangement Contest Winning Track: Boss Theme Category", "dlc": 12, },
    {"title": "Arrangement Contest Winning Track: Instrumental Category", "dlc": 12, },
    {"title": "Arrangement Contest Winning Track: Vocal Category", "dlc": 12, },
    {"title": "CENSORED!!", "dlc": 12},
    {"title": "Crazy Backup Dancers", "dlc": 12},
    {"title": "Grip & Break down !!", "dlc": 12},
    {"title": "Last Occult Fantasy", "dlc": 12},
    {"title": "Special Ability to Excite the Audience feat. Taitson", "dlc": 12, },

    {"title": "Beneath the Purple Cherry Blossoms Once Again", "dlc": "free"},
    {"title": "Farewell Tour", "dlc": "free"},
    {"title": "Flawless Clothing of the Celestials (not)innocent?", "dlc": "free"},
    {"title": "Help me, ERINNNNNN!!", "dlc": "free"},
    {"title": "Maware Gensou Festival", "dlc": "free"},
    {"title": "Megalovania of the Empty Corse", "dlc": "free"},
    {"title": "Necrolovania", "dlc": "free"},
    {"title": "U.N. Owen Was Hero?", "dlc": "free"},
    {"title": "Yurikago no Uta", "dlc": "free"},
]
# fmt: on
