mitama_cards = [
    {"name": "Magic Vision Bullets", "type": "Em"},
    {"name": "The Two of Us, Meeting in the Magic Hour", "type": "Ro"},
    {"name": "Illusionary Barrier - Peace", "type": "Co"},
    {"name": "Area of Forbidden Magic - Radiant", "type": "Ro"},
    {"name": "The Nun Who Overcame Eight Sufferings", "type": "Co"},
    {"name": "Brambly Rose Garden", "type": "Em"},
    {"name": "It Will Never Melt!", "type": "Ro"},
    {"name": "Elegant Servant", "type": "Em"},
    {"name": "No Life Queen", "type": "Co"},
    {"name": "Endless Way of the Sword", "type": "Ro"},
    {"name": "Converging Dreams and Desires", "type": "Em"},
    {"name": "History-Eating Half-Beast", "type": "Ro"},
    {"name": "Wind Priestess", "type": "Co"},
    {"name": "Descendant of the Sun Goddess", "type": "Co"},
    {"name": "Ship Ghost Murasa", "type": "Em"},
    {"name": "Lunatic Dreamer", "type": "Ro"},
    {"name": "Lifestyle of the Head Guardian God", "type": "Ro"},
    {"name": "The Controller of All Emotions", "type": "Co"},
    {"name": "Kappa Brimming With Vitality", "type": "Co"},
    {"name": "Wild Mother Earth", "type": "Co"},
    {"name": "Even Hell's Judgement Relies on the Cat", "type": "Co"},
    {"name": "Midsummer Luciferin", "type": "Ro"},
    {"name": "Rainbow Puppeteer", "type": "Co"},
    {"name": "Inaba's White Rabbit", "type": "Em"},
    {"name": "Jeweled Branch of Hourai", "type": "Co"},
    {"name": "She Knows Not of Big Sister's Heart", "type": "Em"},
    {"name": "Have You Adopted the Decimal System?", "type": "Co"},
    {"name": "Unnatural Phenomenon of Legend", "type": "Em"},
    {"name": "Haniwa Army, Charge!", "type": "Em"},
    {"name": "Holy Child's Great Priest", "type": "Ro"},
    {"name": "Manas-Vijnana Cheer Dancer", "type": "Ro"},
    {"name": "Curse Gods Lord Mishaguji", "type": "Co"},
    {"name": "Moonlit Dullahan", "type": "Co"},
    {"name": "Cherish the Harmony Among People", "type": "Em"},
    {"name": "The Shrine Is Clear Today", "type": "Ro"},
    {"name": "Isn't This a Bother?", "type": "Ro"},
    {"name": "Natural Born Amanojaku", "type": "Em"},
    {"name": "Blue Fleabane", "type": "Ro"},
    {"name": "Foreign Bake-Danuki", "type": "Co"},
    {"name": "Hakurei Shrine", "type": "Em"},
    {"name": "Forest of Magic", "type": "Co"},
    {"name": "Scarlet Devil Mansion", "type": "Ro"},
    {"name": "Hakugyokurou", "type": "Em"},
    {"name": "Eientei", "type": "Co"},
    {"name": "Moriya Shrine", "type": "Ro"},
    {"name": "Palace of the Earth Spirits", "type": "Em"},
    {"name": "Palanquin Ship", "type": "Co"},
    {"name": "Divine Spirit Mausoleum", "type": "Ro"},
    {"name": "Shining Needle Castle", "type": "Ro"},
    {"name": '"Hisouten of All Humanity"', "type": "Em"},
    {"name": "Shining Needle Sword", "type": "Em"},
    {"name": "Knight of the Night", "type": "Co"},
    {"name": "Seven Day Witch", "type": "Co"},
    {"name": "Scarlet Devil", "type": "Ro"},
    {"name": "Let's Solve the Incident!", "type": "Co"},
    {"name": "Hello, Forgotten World", "type": "Em"},
    {"name": '"Water Allocation Trial"', "type": "Ro"},
    {"name": "Flawless Wet-Winged Butterfly", "type": "Ro"},
    {"name": "Year ⑨ Class ⑨", "type": "Ro"},
    {"name": "Engineer at the Water's Edge", "type": "Em"},
    {"name": "Ghost Lifesaver", "type": "Ro"},
    {"name": "Komeiji Summerland", "type": "Co"},
    {"name": "Gung-Ho White Bhikkhuni", "type": "Em"},
    {"name": "Delectable Sake", "type": "Em"},
    {"name": "Ghost Princess", "type": "Em"},
    {"name": "Wire Puller", "type": "Ro"},
    {"name": 'Sword Technique "Cherry Blossom Flutter"', "type": "Em"},
    {"name": "Alien X", "type": "Em"},
    {"name": "The Cherry Forgotten Umbrella", "type": "Ro"},
    {"name": "Rabbit-Rousing Moon Princess", "type": "Ro"},
    {"name": "Hourai Pharmacist", "type": "Ro"},
    {"name": "Smash the Canopy", "type": "Em"},
    {"name": "Dancing on Moonbeams", "type": "Ro"},
    {"name": "Why Do You Linger?", "type": "Ro"},
    {"name": "Manovijnana Backup Dancer", "type": "Em"},
    {"name": '"Her Name: Rival Newspaper Maker"', "type": "Em"},
    {"name": 'Youkai Extermination "Youkai Spoiler"', "type": "Em"},
    {"name": 'Quick Snap "Fast Shot"', "type": "Em"},
    {"name": '"Embryonic Dream"', "type": "Co"},
    {"name": "Unmoving Great Library", "type": "Ro"},
    {"name": "Flying Fantastica", "type": "Co"},
    {"name": "Eternal Fatal Relationship", "type": "Co"},
    {"name": "Youkai Who Protects Humans", "type": "Co"},
    {"name": "Lucid Dreamer", "type": "Co"},
    {"name": "Red and White Queen", "type": "Em"},
    {"name": "Rare and Lazy Ancient Trickster", "type": "Ro"},
    {"name": "We're the Rabbit Alliance!", "type": "Em"},
    {"name": "Sun's Smile", "type": "Em"},
    {"name": "The Strongest Fairy", "type": "Em"},
    {"name": "Loyal Pheasant? Kutaka", "type": "Em"},
    {"name": "Loyal Dog Aunn", "type": "Co"},
    {"name": "Most Sinister God of Poverty", "type": "Co"},
    {"name": "Most Youkai-Like Youkai", "type": "Co"},
    {"name": "Jack-O'-Lantern", "type": "Co"},
    {"name": "Ignis Fatuus", "type": "Co"},
    {"name": "Wicked Witch", "type": "Co"},
    {"name": "Sawyer Invader", "type": "Ro"},
    {"name": "Magical Vampire", "type": "Em"},
    {"name": "Pumpkin Mummy", "type": "Ro"},
    {"name": "Poltergeist Nocturne in C-Sharp Minor", "type": "Ro"},
    {"name": "Merlin Happy Live Show!", "type": "Co"},
    {"name": "Waltz for Layla", "type": "Em"},
    {"name": "Appease the Spirit, Pure Kagura", "type": "Ro"},
    {"name": "Here We Go! Danmaku Cultural Festival!", "type": "Em"},
    {"name": "Distantly Surveying Telegnosis", "type": "Ro"},
    {"name": "Leisurely Shogi", "type": "Ro"},
    {"name": "Go! Passionately Supporting Reporter", "type": "Ro"},
    {"name": "The Moon's Wisdom Before the Board", "type": "Em"},
    {"name": '"Orin, You\'re Being a Nuisance"', "type": "Co"},
    {"name": "Newspaper Reporter's Sponsor Plan!", "type": "Em"},
    {"name": "Autum at the Divine Spirit Mausoleum", "type": "Em"},
    {"name": "Ecstasy Fresh From the Oven", "type": "Em"},
    {"name": "Flame Dance", "type": "Em"},
    {"name": "Safe and Secure Firefighting Squad", "type": "Ro"},
    {"name": "All Souls' Day Bonfire", "type": "Co"},
    {"name": "Cleanup After the Fire Festival", "type": "Ro"},
    {"name": "Taste the Food", "type": "Ro"},
    {"name": "Mellow Aroma of Abundance", "type": "Ro"},
    {"name": "Harvest Festival Without the Goddess", "type": "Ro"},
    {"name": "Moon Harvest Festival", "type": "Em"},
    {"name": "Autumn Is for Eating!", "type": "Co"},
    {"name": "Lakeside Nostalgia", "type": "Em"},
    {"name": "Welcome Hell's Christmas!", "type": "Em"},
    {"name": "Little Oni Christmas", "type": "Em"},
    {"name": "Making It Horrible and Hilarious", "type": "Em"},
    {"name": "The Strongest Gift!", "type": "Co"},
    {"name": "Scarlet Mansion's Holy Night", "type": "Co"},
    {"name": "Perfect Patissier", "type": "Co"},
    {"name": "Woven Friendship", "type": "Co"},
    {"name": "One Thing Missing", "type": "Co"},
    {"name": "Undecided Curriculum", "type": "Co"},
    {"name": "Zeal, Youth, Instructor Inaba!", "type": "Em"},
    {"name": "Hello, Goddess", "type": "Ro"},
    {"name": "Doppelganger in the Window", "type": "Em"},
    {"name": "I'll Give You Half of the World", "type": "Em"},
    {"name": "Do Dogs Curl Up Under the Kotatsu?", "type": "Em"},
    {"name": "Any Duty Together - Green", "type": "Em"},
    {"name": "Any Duty Together - Pink", "type": "Ro"},
    {"name": "A Prime Secret Strategy, Midsummer Power", "type": "Ro"},
    {"name": "Carefree Hell Fairy", "type": "Ro"},
    {"name": "Shuttlecock Smash!", "type": "Co"},
    {"name": "Outfit for a Youkai?", "type": "Co"},
    {"name": "Blocked Third Eye", "type": "Co"},
    {"name": "Welcome to Myourenji Land", "type": "Em"},
    {"name": "Well Done, My General", "type": "Co"},
    {"name": "Chou-Han Master Shaker", "type": "Co"},
    {"name": "Disturbing Bright Sky", "type": "Co"},
    {"name": "New Illusionary History -Next History-", "type": "Em"},
    {"name": "Super Important Jeweled Pagoda", "type": "Em"},
    {"name": "What Can This Eye See?", "type": "Em"},
    {"name": "Pull and Ding-Ding-Ding!", "type": "Em"},
    {"name": "For Every God Found, a God Is Abandoned", "type": "Ro"},
    {"name": "Fated Enemy of Buddhism", "type": "Em"},
    {"name": "Sound Mind, Sound Body", "type": "Ro"},
    {"name": "Miss Sun, Miss Ran, and Miss Yukari", "type": "Ro"},
    {"name": "Rare Visitor to Mayoiga", "type": "Ro"},
    {"name": "Narrowly Getting Away in a Game of Chase", "type": "Ro"},
    {"name": "Today's Whimsical Mischief", "type": "Co"},
    {"name": '"Again, in a New Gensoukyou"', "type": "Co"},
    {"name": "A Day Without Incident Is Empty", "type": "Co"},
    {"name": "Worried About the Mountain's Defense", "type": "Co"},
    {"name": "I Won't Lose to Her This Valentine's", "type": "Co"},
    {"name": "God of Pestilence's Changing Routine", "type": "Co"},
    {"name": "Chinese Girl's Tea Performance", "type": "Co"},
    {"name": "Chic Maid and the Unmovable Great Library", "type": "Em"},
    {"name": "Enough Magic to Materialize Emotion", "type": "Co"},
    {"name": "The Harvest Goddess Favors Cacao Beans?", "type": "Em"},
    {"name": '"Sunterranean Rose"', "type": "Ro"},
    {"name": "Tenryuu Ultra Battle! Deadly Growl!", "type": "Em"},
    {"name": "Eyes Never Clouded by Despair", "type": "Em"},
    {"name": "Illuminated by Starlight", "type": "Co"},
    {"name": 'Sake Lake "A River of Hell Souvenirs"', "type": "Em"},
    {"name": "Drunken Evening, Reminiscing Farewells", "type": "Em"},
    {"name": "Grasping a Small Determination", "type": "Co"},
    {"name": "Pungence of Envy and Nonchalance", "type": "Co"},
    {"name": "With Love to a Treasured Person", "type": "Co"},
    {"name": "Sweet Scent and Unyielding Tongue", "type": "Ro"},
    {"name": "Poverty God's Sweet Happiness", "type": "Co"},
    {"name": "I, on a Special Sincere Day", "type": "Co"},
    {"name": "Sanae's Shining Valentine ☆", "type": "Ro"},
    {"name": "Dancing in Secret", "type": "Ro"},
    {"name": "My Very Own Hina Doll", "type": "Ro"},
    {"name": "Becoming a Grassroots Volunteer", "type": "Co"},
    {"name": "One Tasste and There's No Calming Down", "type": "Ro"},
    {"name": "Dancing Threads Like a Prism", "type": "Ro"},
    {"name": "Firefly Spotlight", "type": "Co"},
    {"name": "Awakened Spring Fairy", "type": "Co"},
    {"name": "Quiet Spring, Wrapped in Sunshine", "type": "Co"},
    {"name": "Melody -Smile for the Lingering Snow-", "type": "Co"},
    {"name": "Beginnings and the Symphonia of Awakening", "type": "Ro"},
    {"name": "Soaring Black and White Wings", "type": "Co"},
    {"name": "From Longevity, Love for Fleeting Life", "type": "Ro"},
    {"name": "Four Season With the Shikigami", "type": "Ro"},
    {"name": "Cat Joyfully Frolicking in Spring", "type": "Ro"},
    {"name": "Dissolving Into the Night, Alone", "type": "Ro"},
    {"name": "Bishamonten's Break", "type": "Em"},
    {"name": "The Cup We Shared That Day", "type": "Ro"},
    {"name": "Produse Chaos, Gnawing and Tearing", "type": "Em"},
    {"name": "Silent Heron, Dream-Bringer Baku", "type": "Em"},
    {"name": "Discover a New Fashion!", "type": "Em"},
    {"name": "I'm Here, Time for the Show!", "type": "Em"},
    {"name": "Forgotten Umbrella, Unforgettable Smile", "type": "Ro"},
    {"name": "The Sage Comes to Speak of the Moon", "type": "Em"},
    {"name": "Sky Journey, Ahoy!", "type": "Ro"},
    {"name": "Secret Laughter -White Fox Whispers-", "type": "Ro"},
    {"name": "\\Cluck-Cluck☆/ Niwatari Panic!", "type": "Ro"},
    {"name": "Mouse Monarch's Painful Awakening", "type": "Co"},
    {"name": "The Futatsuiwa Family's Chivalry", "type": "Ro"},
    {"name": "Inverted Pierrot and Little Braver", "type": "Ro"},
    {"name": "Currency Is Life in the Information Wars", "type": "Co"},
    {"name": '"Moriya Wars: Suwako Vs. Kanako"', "type": "Co"},
    {"name": "We Protect, So There Is Peace", "type": "Co"},
    {"name": "Looking Down at the Froggie's Precincts", "type": "Co"},
    {"name": "The End of Spring Away From the Tumult", "type": "Ro"},
    {"name": "First Step to a New World", "type": "Co"},
    {"name": "Come Out, Scrolls of Frolicking Animals", "type": "Ro"},
    {"name": "Blue Sky and Cloud Clusters Above", "type": "Em"},
    {"name": "Sun God of Blazing Hell", "type": "Ro"},
    {"name": "The Scenes of That Day, Now Distant", "type": "Ro"},
    {"name": 'Legendary Force "Discus Shatters World"', "type": "Ro"},
    {"name": "Meiling's Pentathlon -Where I Belong-", "type": "Co"},
    {"name": "Stop in the Warm Spring", "type": "Ro"},
    {"name": "Bridge Sat on by a Princess", "type": "Co"},
    {"name": "Fleeting Karma -Butterfly Dancing-", "type": "Co"},
    {"name": "My Summer Adventure", "type": "Co"},
    {"name": "Let's Meet Again Next Spring", "type": "Co"},
    {"name": "Beautiful East Asia", "type": "Em"},
    {"name": "Bamboo Crazy Dance", "type": "Co"},
    {"name": "What Is Hidden Is More Beautiful", "type": "Em"},
    {"name": "Master of Idola", "type": "Em"},
    {"name": "The Girl With the Closed Third Eye", "type": "Em"},
    {"name": '"Don\'t Search for Me"', "type": "Em"},
    {"name": "Palm of the Politician's Hand", "type": "Co"},
    {"name": "Beast Metropolis in Fierce Battle", "type": "Em"},
    {"name": "Drill and Romance Onboard!", "type": "Co"},
    {"name": "Outsider Girls", "type": "Co"},
    {"name": "Indelible Sin and Eternal Mini Garden", "type": "Co"},
    {"name": "Floating Through the World -Occult Evening-", "type": "Co"},
    {"name": "Thread That Weaves the Soul and Vessel", "type": "Ro"},
    {"name": "Sweet Momentary Pleasure", "type": "Co"},
    {"name": "Mad Head Twilight", "type": "Ro"},
    {"name": "Dance and Sing, Illusionary Tap Dancers", "type": "Ro"},
    {"name": "Where Souls and Memories Rest", "type": "Ro"},
    {"name": "Lively Tsukumo Shopping ☆", "type": "Ro"},
    {"name": "Glass Tone and Summer Visit", "type": "Em"},
    {"name": "Dichotomous Emotions", "type": "Ro"},
    {"name": "Sunshine, Books, and I", "type": "Em"},
    {"name": "Honorless, Quiet Frenzy", "type": "Em"},
    {"name": "Metropolis UFO Romance", "type": "Em"},
    {"name": "All Is Scattering Blossoms", "type": "Em"},
    {"name": "That Lion Is Gensoukyou's Dog", "type": "Ro"},
    {"name": "Ignorance Is Bliss", "type": "Em"},
    {"name": "Feelings of the Nine-Tailed Fox With Shikigami", "type": "Ro"},
    {"name": "I Wish I Could Die Under Spring Flowers", "type": "Em"},
    {"name": "Devil Sister", "type": "Co"},
    {"name": "Brave, Peerless, and Free", "type": "Ro"},
    {"name": "Multicolored Vivid Creator", "type": "Ro"},
    {"name": "Never Let the Target Get Away!", "type": "Ro"},
    {"name": "Memories of a Summer Walk With You", "type": "Em"},
    {"name": "Beneath Blazing Flowers", "type": "Ro"},
    {"name": "The Night the Magpie Flies", "type": "Em"},
    {
        "name": "The Dragon Palace Messenger Appears With a Gust of Wind",
        "type": "Em",
    },
    {"name": "The Mythical Oni of Oe's Plain Life", "type": "Em"},
    {"name": "All or Bust: Shinmyoumaru Fishing Tale", "type": "Em"},
    {"name": "Is It Ready? ~Survival of Poverty God~", "type": "Co"},
    {"name": "Look! New Chaos Dance of the Great Clans", "type": "Em"},
    {"name": "Chinese Girl Defeated by the Midsummer", "type": "Co"},
    {"name": "Shine, Emerald Resort!", "type": "Co"},
    {"name": "Sun-Dappled Summer Vacation", "type": "Co"},
    {"name": "Blue Sky Summer Ranger", "type": "Em"},
    {"name": "Fine Beauty, Lit by Neon", "type": "Co"},
    {"name": "Perfect Maid of the Midsummer Sea", "type": "Co"},
    {"name": "False Summer Vacation", "type": "Em"},
    {"name": "Perimission to Kill ~ Just Slash", "type": "Em"},
    {"name": "Producer Seiga Kaku's Reasons", "type": "Em"},
    {"name": "Amazing Idol Announcement!", "type": "Ro"},
    {"name": "I, the Unsung Loyal Jiangshi", "type": "Em"},
    {"name": "Go, Go! Aerial Cruise!", "type": "Em"},
    {"name": "A Pure Dream World", "type": "Ro"},
    {"name": "The One-Winged Sage", "type": "Ro"},
    {"name": "Goddess's Ultimate Live Project", "type": "Ro"},
    {"name": "Sound Doesn't Speak, It Only Echoes", "type": "Co"},
    {"name": "The Long Night Harlequin", "type": "Ro"},
    {"name": "Dazzling Large Flower", "type": "Co"},
    {"name": "Cooling Off in August", "type": "Co"},
    {"name": "Wealth or Ruin Beckons", "type": "Co"},
    {"name": "Protector of the Promised Land", "type": "Co"},
    {"name": "Secure? Bridge Princess Defense Legend", "type": "Em"},
    {"name": "Raging Gale Monster", "type": "Co"},
    {"name": "Seeking the Best Shot in Gensoukyou", "type": "Ro"},
    {"name": "Unmelting Ice and Unbreaking Heart", "type": "Ro"},
    {"name": "Smilling Happy Day", "type": "Ro"},
    {"name": "Then and Now, You and I", "type": "Ro"},
    {"name": "The Scent of Happiness and Daily Life", "type": "Em"},
    {"name": "Dream or Reality, Sweet Night", "type": "Ro"},
    {"name": "Irreversible Chronos", "type": "Em"},
    {"name": "Blooming Afternoon Tea Time", "type": "Em"},
    {"name": "Did You Lose This?", "type": "Co"},
    {"name": "What Do Azaleas Taste Like?", "type": "Em"},
    {"name": "Autumn Strolls With a Leaf of Happiness", "type": "Co"},
    {"name": "My Unknown World", "type": "Em"},
    {"name": "Hourai Clinic", "type": "Em"},
    {"name": "Unconfined Full Moon Night", "type": "Co"},
    {"name": "Power of the Ferocious Tiger", "type": "Co"},
    {"name": "Reminiscing on the Night of a Full Moon", "type": "Co"},
    {"name": "Kawashiro Circus Under the Autumn Sky", "type": "Ro"},
    {"name": "Long Lives and Short Banquets", "type": "Co"},
    {"name": "Reminiscing of Summers Past", "type": "Ro"},
    {"name": "Grand Concert Dedicated to You", "type": "Co"},
    {"name": "Ever Since ~ Are you?", "type": "Em"},
    {"name": "What Makes Me Who I Am", "type": "Co"},
    {"name": "Prayer for Red Moon, Feast, and Reverie", "type": "Ro"},
    {"name": "Words Etched in the Past ~ For you.", "type": "Em"},
    {"name": "A Girl's Summer Day", "type": "Em"},
    {"name": "Splash ☆ Comet", "type": "Em"},
    {"name": "Clear Autumn Sky, Enigmatic Blossoms", "type": "Em"},
    {"name": "Hourai's Human Form", "type": "Ro"},
    {"name": "Nameless Existence", "type": "Co"},
    {"name": "Misty Lake", "type": "Em"},
    {"name": "Human Village", "type": "Co"},
    {"name": "Bamboo Forest of the Lost", "type": "Ro"},
    {"name": "Youkai Mountain", "type": "Em"},
    {"name": "Kirisame Magic Shop", "type": "Co"},
    {"name": "Heaven", "type": "Ro"},
    {"name": "Kasen's Residence", "type": "Em"},
    {"name": "Myouren Temple", "type": "Co"},
    {"name": "Mayoiga", "type": "Ro"},
    {"name": "Lorelei Sings for You", "type": "Em"},
    {"name": "Beyond the Threshold", "type": "Co"},
    {"name": "Karmic Relationships Born From Drunkenness", "type": "Ro"},
    {"name": "Join Us, Lively Dancer!", "type": "Em"},
    {"name": "Let Steam and Machines Carry Your Dream", "type": "Co"},
    {"name": "Fluid and Alluring Performance", "type": "Ro"},
    {"name": "The Path of Knowledge Is Endless", "type": "Em"},
    {"name": "Multicultural Haven", "type": "Co"},
    {"name": "Forgotten Garden of Eden", "type": "Ro"},
    {"name": "The Invited", "type": "Em"},
    {"name": "Embracing Autumn", "type": "Co"},
    {"name": "As the God of War Commands", "type": "Ro"},
    {"name": "The Body Decays but Love Remains", "type": "Em"},
    {"name": "Fight for Sweets☆", "type": "Co"},
    {"name": "The Sound of This Flute Is for You", "type": "Ro"},
    {"name": "Stained by False Blood ~ Vampire Night.", "type": "Em"},
    {"name": "Echoes of a Genuinely Wicked Wish", "type": "Co"},
    {"name": "Unconventional, Formless Desire-Eater", "type": "Ro"},
    {"name": "Let's begin our Gensoukyou", "type": "Em"},
]
