from typing import Literal, NotRequired, TypedDict


class SongData(TypedDict):
    title: str
    dlc: NotRequired[int | Literal["free"]]


song_groups_to_songs: dict[str, list[str]] = {
    "Base Songs": [
        # this song doesn't seem to exist??
        # "A flower blooming on phantasm",
        "Akaboshi Mizeraburu ~Haiokuhen",
        "Akeboshi Rocket",
        "An stoirm",
        "Bad Apple!! feat.nomico",
        "Blaze Up Song",
        "Border of Life",
        "Breaking the Silence",
        "Cirno no Perfect Sansuu Kyoushitsu",
        "Crimson Belvedere ~ Eastern Dream...",
        "DREAMIN' TURBO [DJ Command Remix]",
        "Danzai ha Amaneku Ningen no Motoni",
        "Ecstatic Dreamers",
        "Epikurosu no niji ha moumienai",
        "Fall of Fall",
        "Fox Bullet",
        "Fragments",
        "From Lost To Exequistra",
        "Gensoukyou Fushigi Daihakken V2",
        "HANIPAGANDA",
        "Hakanakimono Ningen",
        "Hartmann's Youkai Girl",
        "Haruka Tooku Haruka Kanata",
        "Help me, ERINNNNNN!!",
        "Iroha Nioedo Cirinuruwo",
        "Kakoinaki Yo wa Ichigo no Tsukikage",
        "Karakuri Doll",
        "Karma D-Live",
        "Kegarematoitekagomekagome",
        "Knight of Nights",
        "Kuroi Umi ni Akaku ~Legendary Fish",
        "Kyousyuu no Rondo",
        "LOSTPHANTASIA",
        "Live or live!",
        "Lucent Wish",
        "MATSUYOI Nightbug",
        "Machibito ha Kozu.",
        "Meguru Harvest",
        "Mischievous Sensation",
        "Native Faith（Dankagu special ver.）",
        "Night Flight Believer",
        "Ougon Kouro",
        "Phantom Band ~ Phantom Ensemble",
        "Pure Furies ~ Whereabouts of the Heart",
        "Re:Unknown X",
        "Reach for the Moon, Immortal Smoke",
        "Reisen Occultia [Touhou Shinpiroku Re:Arange]",
        "Resonance ~ What Makes Me Who I Am",
        "Sadistic Love - Danmakukagura Edit",
        "Saishuu kichiku imouto Flandre-S",
        "Sayounara. Arigatou.",
        "Scarlet Keisatsu no Ghetto Patrol 24ji",
        "Spider's Blood",
        "Spring of Dreams",
        "Starlight Dance Floor (D.M.K. edit)",
        "Tengu no Hana（feat.TAG）",
        "Tenimuhou",
        "The Mirage of That Day",
        "Tsuki ni Murakumo Hana ni Kaze",
        "Ttewi! ~Eientewi Ver~",
        "U.N. Owen Was Her?",
        "Unprivileged Access",
        "Uso to Doukoku",
        "White Lotus...",
        "Yozora to Ningyou",
        "Yukemuri TamaOnSen II",
        "drizzly rain",
        "snow amber Remix",
    ],
    "Free DLC": [
        "Beneath the Purple Cherry Blossoms Once Again",
        "Farewell Tour",
        "Flawless Clothing of the Celestials (not)innocent?",
        # listed on their website under Free DLC, but also under base? lol
        # "Help me, ERINNNNNN!!",
        "Maware Gensou Festival",
        "Megalovania of the Empty Corse",
        "Necrolovania",
        "U.N. Owen Was Hero?",
        "Yurikago no Uta",
    ],
    "DLC 1": [
        "Bad Apple!! feat.nomico (Tetsuya Komuro Remix)",
        "Christmas Bomb!!",
        "Dial Connected",
        "Entrusting this World to Idols(marasy piano ver.)",
        "Genmu",
        "Gensou Syndrome",
        "Gensou no Satellite",
        "Hanamaru! Saikyo Hyper Cirno",
        "Hell's Sun",
        "Hitorisizuka（Marcia Cover Version）",
        "Howling",
        "INTERNET SURVIVOR",
        "Love-colored Master Spark",
        "M. O. N. E. Y. (Dankagu Special REMIX Ver.)",
        "Museimei Saafesu",
        "Onerule・Gamechanger",
        "POKER FACE",
        "PanneDemonology",
        "Paranoia",
        "SACRIFICE",
        "Saigetsu",
        "Tenkyuu Tenge Otohanabi",
        "The Karasu Wind",
        "Trance Dance Anarcky",
        "Uki Yomichi (feat. Ranko, Utenkekkou)",
    ],
    "DLC 2": [
        "Against, Perfect Cherry Blossom",
        "Amatsukazeyo",
        "Can't look away",
        "Desire Drive",
        "Flower Flag",
        "Gensokyo Millennium ~ History of the Moon",
        "Hitotsuyogari no Touhikou",
        "King of the Sekkyou",
        "LOVE EAST",
        "Mami Mami Zone",
        "Marisa Stole the Precious Thing",
        "Never Come Undone",
        "Painting The Lips Red",
        "Pandora",
        "Rainy, rainy days",
        "SAMURAI GHOST GIRL, KILL! KILL!",
        "SWEET BLUE ICE",
        "Scream out!",
        "Shinreibyou Akimatsuri!",
        "Shout It Out Loud!!!",
        "Shoutoku Densetsu ~ True Administrator",
        "Tiny Little Adiantum",
        "Utakata, Ai no Mahoroba",
        "Youyoubakko ~ Who done it!",
        "far away",
    ],
    "DLC 3": [
        "23145EASONS",
        "Aestivalis(Danmakukagura Edit)",
        "Aitsu ha Ikasama wo Shiteiru",
        "Atashimania",
        "Aunn by me",
        "Ayakashi set 14 Another ~Yoru ga Oritekuru",
        "BURN IN HELL",
        "Chi no Iro ha Kiiro",
        "Ford Stream",
        "Gekokujoujou",
        "Gensou Kappa Kousinkyoku(feat.ｙｔｒ)",
        "Hands(feat. AO, Rappubito)",
        "Hollow Masquerade",
        "Kachoufuugetsu",
        "Kagerou-chan Tsuki ni Hoeru (Dankagu Edit)",
        "Konya, Syojo jya Irarenai",
        "Liminality",
        "Night's Dream (D.M.K. edit)",
        "SEE YOU AGAIN!",
        "Solid",
        "Sweets Time",
        "The Shining Law of the Strong Eating the Weak",
        "USATEI 20XX",
        "Unconscious Requiem（cosmobsp rmx）",
        "WARNING×WARNING×WARNING",
        "hareruya ga kikoeru",
    ],
    "DLC 4": [
        "Akutagawa Ryuunosuke no Kappa",
        "Charisma Rengoku Tenshin",
        "Dancing Dollz feat. cold kiss",
        "Fabulous",
        "GAME OVER (In Disarray)",
        "Getsurei 11.3 no Candle Magic",
        "HAZARD☢AREA",
        "Hakurei Jinja Chounaikai Ondo",
        "Hopeless Discord",
        "Hoshi wo Mawase Tsuki yori Hayaku",
        "Iconoclasm",
        "Ilias",
        "Kanbu de Tomatte Sugu Tokeru ~Kyouki no Udongein",
        "Kyouen",
        "Lezamari demo tsurakunai!!",
        "Lotus Love",
        "Marionette Metropolis",
        "Mishaguji Empire",
        "Non-Stop Ringing Heartbeats",
        "Romantic Fall feat. Ayakura Mei",
        "Septette for a Dead Princess",
        "Shunkan Photography",
        "Tenshi no Udedameshi",
        "VOLUPTÉ (Game Edit)",
        "flanticnight",
        "sparkle light",
        "supernatural",
    ],
    "DLC 5": [
        "Heaven and earth are ruled by my [X]VII divine light",
        "Love-Colored Master Spark ~ NEETs ver.",
        "Rock 'n' Rock 'n' Beat",
        "Saishuu kichiku imouto Flandre-S(Sasuke Haraguchi was Brutal? remix)",
        "Sekai Hifuu Club-ka Keikaku",
        "Stairway to Cherry Blossoms",
        "The Footsteps That Summon Winter",
        "The Gensoukyou the Gods Loved",
        "Ultimate taste",
        "Wind of Faith",
    ],
    "DLC 6": [
        "HUNDRED DUOVIGINTILLION ARROWS",
        "Idoratrize World",
        "Lamento (Dankagu Edit)",
        "Nobody Can Stop Bankichan",
        "Rough Sea (Game Edit)",
        "Subliminal Seduction",
        "Tenacity",
        "The World Is Made From Cuteness",
        "Tsukikake (feat. Coro)",
        "Witches Rule (SIRIUS Remix)",
    ],
    "DLC 7": [
        "Crepusculum",
        "Desire Drive",
        "Exteeend!!",
        "Futeikei Avatar",
        "Kowareta Ningyo no March (SA ver.)",
        "Midnight Syndrome",
        "Mishery",
        "STNC",
        "sharp edge",
        "・ー・・ ーーー ・・・ー ・",
    ],
    "DLC 8": [
        "5byo Kakumei Zen'ya",
        "HEAT WAVER!(feat. Rappubito, Fra)",
        "Heart in Wonderland",
        "Hiiro Gekka Kyosho no Zetsu 15th Anniversary Remix nayuta.ver",
        "Maiden's Capriccio ~ Dream Battle",
        "PRESERVED VAMPIRE",
        "Re:Border of Life",
        "Touhou Youyoumu ~the maximum moving about~",
        "Utakata",
        "myth?",
    ],
    "DLC 9": [
        "Absolute Queen",
        "Alice Maestera(REBIRTHED)",
        "Calamity Fortune",
        "Entrust This World to Idols ~ Idolatrize World",
        "Kodoku Tsuki",
        "Necromantic",
        "Star-Colored Night Sky",
        "Syuki Rai Rai!",
        "Xeno Phantasm",
        "kero9destiny - type130",
    ],
    "DLC 10": [
        "A Soul as Scarlet as a Ground Cherry",
        "Bang Bang!",
        "DA-DA-ON-SEN (feat. Utenkekkou)",
        "Flame of Nuclear (Dankagu Edit)",
        "Lunatic Princess",
        "Night Falls ～ Evening Star LSDj Remix (Dankagu Edit)",
        "Sunlight Diamonds (Violet Delta Remix)",
        "The Replica Sneers",
        "Vampire Mate",
        "Who killed U.N.Owen",
    ],
    "DLC 11": [
        "Call of Mirage (Game Edit)",
        "Kare Kishi ni Saku",
        "MagicPhilia (Chimera Edit)",
        "New Arrangement by D-Drive vs. pomaira m9(^Д^)",
        "New Arrangement by Galactic Revolver × UNKNOWN BEATS",
        "New Arrangement by INORAI / Girls Logic Observatory / AbsoЯute Zero",
        "New Arrangement by Sekkenya feat. beatMARIO",
        "Take Thy Danmaku In Hand, O Bulletphiles",
        "Twin Tailed Step",
        "Voile, the Magic Library (Jazz & Chill Edit)",
    ],
    "DLC 12": [
        "A Dream Transcending Space-time",
        "Armageddon",
        "Arrangement Contest Winning Track: Boss Theme Category",
        "Arrangement Contest Winning Track: Instrumental Category",
        "Arrangement Contest Winning Track: Vocal Category",
        "CENSORED!!",
        "Crazy Backup Dancers",
        "Grip & Break down !!",
        "Last Occult Fantasy",
        "Special Ability to Excite the Audience feat. Taitson",
    ],
}
